#!/bin/bash

#displays views from 4 different usb cameras on 4 different networked computers

mplayer http://192.168.1.14:8080 -user root -passwd passwordgoeshere -fps 15&

sleep 3

mplayer http://192.168.1.7:8081 -user root -passwd passwordgoeshere -fps 15&

sleep 3

mplayer http://192.168.1.16:8082 -user root -passwd passwordgoeshere -fps 15

sleep 3

mplayer http://192.168.1.17:8083 -user root -passwd passwordgoeshere -fps 15

